### ISSUE TITLE
Error: All RSS feed downloads failed. Is the network down?

### ISSUE THREAD

**Issue by krosseyed** [boustrophedon/rss-actions#5]
I am unable to use this program as when I am trying to update feeds, I get the following error:

Error: All RSS feed downloads failed. Is the network down?

I can confirm I can reach github via ping.

**Comment by boustrophedon** [comment]
Yeah it should probably print one of the error messages in addition to that message.

**Comment by krosseyed** [comment]
What if that is the only output? Do you think I may have missed a dependency when pulling the crate down? I had to install a few things through apt-get since I am using this on Ubuntu Server 22.04.

**Comment by boustrophedon** [comment]
Oh sorry, I meant that I should add code so that it prints the error message from one of the failures. Out of curiosity, what did you have to install via apt?

**Comment by krosseyed** [comment]
I had to install libsqlite3-dev and pkg-config to get the build process to work.

**Comment by boustrophedon** [comment]
Ah okay, that makes sense. I'll try to get a new version out soon with the extra error message and a bundled sqlite so you don't need the packages installed.

Thanks for the report!

**Comment by krosseyed** [comment]
Thanks @boustrophedon! I really like the idea of this program as I have a common use case that rss-actions solves. It allows me to easily create an update process to activate an automation script, and I would love to test this out again when you have a new version.

**Comment by boustrophedon** [comment]
It was bothering me so I made the changes today and published 0.3 to crates.io. Let me know if this resolves your issues.

**Comment by krosseyed** [comment]
@boustrophedon, It looks like I have a new error!

```
Error: All RSS feed downloads failed. Is the network down? Example error:
 Could not parse snipeit rss feed from url https://github.com/snipe/snipe-it/tags.atom
```

Is Atom supported? I would have assumed so since its a fairly common file type for consuming RSS feeds.

**Comment by krosseyed** [comment]
I can also confirm that curl and wget work on the url provided, on the machine I am trying to run rss-actions on.

**Comment by boustrophedon** [comment]
Ah, that would explain it. There's no atom support right now, and I don't really have the time to work on it at the moment, sorry.

**Comment by krosseyed** [comment]
I appreciate your efforts and I will look for a way to grab that data using rss instead of atom.

I see issue #7 and I will close this in response to you putting that on the todo list.
